version: "2"

services:
  bitwardenrs:
    image: bitwardenrs/server:latest
    container_name: bitwardenrs
    volumes:
      - /home/username/docker-data/bitwardenrs:/data/
    ports:
      - 8100:80
    restart: unless-stopped