version: '2.3'

services:
  statping:
    container_name: statping
    image: statping/statping:latest
    restart: always
    volumes:
      - /home/username/docker-data/statping:/app
    environment:
      DB_CONN: sqlite
    ports:
      - 8476:8080
