web:
  image: 'ulm0/gitlab'
  restart: always
  hostname: 'gitlab.domain.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://gitlab.domain.com:9090'
      gitlab_rails['gitlab_shell_ssh_port'] = 2224
  ports:
    - '9090:9090'
    - '2224:22'
  volumes:
    - '$HOME/docker-data/gitlab/config:/etc/gitlab'
    - '$HOME/docker-data/gitlab/logs:/var/log/gitlab'
    - '$HOME/docker-data/gitlab/data:/var/opt/gitlab'