version: '2.1'

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/Chicago
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_SCHEDULE=0 0 16 ? * THU
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=username@yahoo.com
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=username@icloud.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.mail.yahoo.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=app_specific_password
      - WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG=SERVER_NAME Server -- Container updates
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=username@yahoo.com
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
    restart: unless-stopped